apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
  labels:
    app: ebs-dynamic
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi