apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
  labels:
    app: ebs-dynamic
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    app: ebs-dynamic
spec:
  containers:
    - name: ebs-dynamic
      image: nginx
      volumeMounts:
        - name: ebs-dynamic-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: ebs-dynamic-volume
      persistentVolumeClaim:
        claimName: ebs-dynamic
---

apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic-svc
  labels:
    app: ebs-dynamic
    env: dev
spec:
  selector:
    app: ebs-dynamic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer