kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-002a3479d803ec355
  directoryPerms: "700"
  # gidRangeStart: "1000" # optional
  # gidRangeEnd: "2000" # optional
  basePath: "/expense" # optional
  # subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
  # ensureUniqueDirectory: "true" # optional
  # reuseAccessPoint: "false" # optional
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic-pod
  labels:
    app: efs-dynamic-pod
spec:
  containers:
    - name: efs-dynamic-container
      image: nginx
      volumeMounts:
        - name: efs-dynamic-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-dynamic-volume
      persistentVolumeClaim:
        claimName: efs-dynamic-claim
---
apiVersion: v1  
kind: Service
metadata:
  name: efs-dynamic-svc
  labels:
    app: efs-dynamic-pod
    env: dev
spec:
  selector:
    app: efs-dynamic-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer