apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:9
    command: ["/bin/bash", "-c",  "sleep 100"]

# containers inside same pod could communicate with each other using localhost and shared volumes and share same network namespace