apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: expense
    environment: dev
    component: labels
spec:
  containers:
  - name: labels
    image: nginx:mainline-alpine3.20-slim