apiVersion: v1
kind: Pod
metadata:
  name: environment
  labels:
    project: expense
    environment: dev
    component: env
spec:
  containers:
    - name: environment
      image: nginx:latest
      env:
      - name: db_host
        value: "mysql.test.db.com"
      - name: config_url
        value: "configmgr.test.com"