apiVersion: v1
kind: Pod
metadata:
  name: environment
  lables:
    project: expense
    environment: dev
    component: env
spec:
  containers:
    - name: environment
      image: nginx:latest
      env:
        - name: db_host
          value: "mysql.test.db.com"
        - name: config_url
          value: "configmgr.test.com"
      resources:
        requests:
          cpu: 100m
          memory: 60Mi
        limits:
          cpu: 120m
          memory: 120Mi