apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  labels:
    project: expense
    environment: dev
    component: configmap
data:
  db_host: "mysql.test.db.com"
  config_url: "configmgr.test.com"


