apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    project: expense
    environment: dev
    component: configmap
spec:
  containers:
    - name: nginx-cm
      image: nginx
      envFrom:
        - configMapRef:
            name: nginx-cm
      # env:
      #   - name: db_host
      #     valueFrom:
      #       configMapKeyRef:
      #         name: nginx-cm
      #         key: db_host
      #   - name: config_url
      #     valueFrom:
      #       configMapKeyRef:
      #         name: nginx-cm
      #         key: config_url