apiVersion: v1
kind: Pod
metadata:
  name: load-secrets
  labels:
    project: expense
    environment: dev
    component: load-secrets
spec:
  containers:
    - name: load-secrets
      image: nginx:1.14.2
      envFrom:
        - secretRef:
            name: db-secret