apiVersion: v1
kind: Pod
metadata:
  name: loadbalancer
  labels:
    project: expense
    environment: dev
    component: loadbalancer
spec:
  containers:
  - name: loadbalancer
    image: nginx:1.14.2
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    project: expense
    environment: dev
    component: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    project: expense
    environment: dev
    component: loadbalancer