apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    project: expense
    environment: dev
    component: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      project: expense
      environment: dev
      component: frontend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        component: frontend
    spec:
      containers:
        - name: nginx-rs
          image: nginx:alpine-slim
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 128m
              memory: 128Mi
---

kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  labels:
    project: expense
    environment: dev
    component: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    project: expense
    environment: dev
    component: frontend


# replica set makes sure that a specified number of pod replicas are running at any given time. 
# but it does not update the pods when the template is changed. the pods need to be deleted and recreated for the changes to take effect.
# deployment is a higher-level concept that manages replica sets and provides declarative updates to pods along with a lot of other useful features.
# deployment is recommended way to manage the creation and scaling of pods.
