apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    project: expense
    environment: dev
    component: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      environment: dev
      component: deployment
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        component: deployment
    spec:
      containers:
        - name: nginx-deployment
          image: nginx:alpine-slim
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 128m
              memory: 256Mi				  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    project: expense
    environment: dev
    component: deployment
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    component: deployment
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30889

# A Deployment is a higher-level concept in Kubernetes that manages ReplicaSets and provides declarative updates to Pods. 
# This means that instead of manually creating and managing individual Pods, you define the desired state of your application in a 
# Deployment, and Kubernetes takes care of creating and maintaining the necessary Pods to match that state.

# Deployments offer several useful features, including the ability to perform rolling updates, rollbacks, and scaling of Pods.
# Rolling updates allow you to update your application to a new version without downtime by gradually replacing old Pods with new 
# ones. If something goes wrong during an update, you can easily roll back to a previous version. Additionally, Deployments make 
# it easy to scale your application up or down by adjusting the number of replicas, ensuring that the desired number of Pods is 
# always running.

# Overall, using a Deployment is the recommended way to manage the creation and scaling of Pods in Kubernetes, as it simplifies 
# the process and provides powerful tools for maintaining the desired state of your application.